# CH 6. 자유자재로 데이터 가공하기

In [1]:
import pandas as pd
import numpy as np

## 6-1 데이터 전처리 - 원하는 형태로 데이터 가공하기

## 6-2 조건에 맞는 데이터만 추출하기

### 조건에 맞는 데이터만 추출하기

In [2]:
exam = pd.read_csv('data/exam.csv')
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [3]:
exam.query('nclass==1')

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58

In [4]:
exam.query('nclass==2')

   id  nclass  math  english  science
4   5       2    25       80       65
5   6       2    50       89       98
6   7       2    80       90       45
7   8       2    90       78       25

In [5]:
exam.query('nclass!=1')

    id  nclass  math  english  science
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

### 초과, 미만, 이상, 이하 조건 걸기

In [6]:
exam.query('math>50')

    id  nclass  math  english  science
1    2       1    60       97       60
6    7       2    80       90       45
7    8       2    90       78       25
10  11       3    65       65       65
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [7]:
exam.query('math<50')

    id  nclass  math  english  science
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
8    9       3    20       98       15
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12

In [8]:
exam.query('english>=50')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [9]:
exam.query('english<=80')

    id  nclass  math  english  science
4    5       2    25       80       65
7    8       2    90       78       25
10  11       3    65       65       65
14  15       4    75       56       78
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87

### 여러 조건을 충족하는 행 추출하기(AND)

In [10]:
exam.query("nclass==1 & math>=50")

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60

In [11]:
exam.query("nclass==1 and math>=50") # 위와 동일한 결과

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60

### 여러 조건 중 하나 이상 충족하는 행 추출하기(OR)

In [12]:
exam.query('math >=90 | english >= 90')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
3    4       1    30       98       58
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
12  13       4    46       98       65
15  16       4    58       98       65

In [13]:
exam.query('math >=90 or english >= 90') # 위와 동일

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
3    4       1    30       98       58
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
12  13       4    46       98       65
15  16       4    58       98       65

### 목록에 해당하는 행 추출하기

In [14]:
exam.query('nclass==1 or nclass==3 or nclass==5')

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [15]:
exam.query('nclass in [1, 3, 5]') # 위와 동일

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

### 추출한 행으로 데이터 만들기

In [16]:
nclass1 = exam.query('nclass==1')

nclass2 = exam.query('nclass==2')

In [17]:
nclass1['math'].mean()

np.float64(46.25)

In [18]:
nclass2['math'].mean()

np.float64(61.25)

### 문자 변수를 이용해 조건에 맞는 행 추출하기

In [19]:
df = pd.DataFrame({
    "sex": ['F', 'M']*2,
    "country": ['Korea', 'China', 'Japan', 'USA']
})
df

  sex country
0   F   Korea
1   M   China
2   F   Japan
3   M     USA

In [20]:
df.query('sex=="F" and country=="Korea"')

  sex country
0   F   Korea

### 변수를 이용해 추출하기

In [21]:
var = 3
exam.query('nclass==@var')

    id  nclass  math  english  science
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32

## 6-3 필요한 변수만 추출하기

### 변수 추출하기

In [22]:
exam['math'] # math 추출

0     50
1     60
2     45
3     30
4     25
5     50
6     80
7     90
8     20
9     50
10    65
11    45
12    46
13    48
14    75
15    58
16    65
17    80
18    89
19    78
Name: math, dtype: int64

In [23]:
exam[['math']] # 시리즈가 아닌 데이터프레임으로 추출

    math
0     50
1     60
2     45
3     30
4     25
5     50
6     80
7     90
8     20
9     50
10    65
11    45
12    46
13    48
14    75
15    58
16    65
17    80
18    89
19    78

In [24]:
exam[['nclass', 'math']] # 여러 변수 추출

    nclass  math
0        1    50
1        1    60
2        1    45
3        1    30
4        2    25
5        2    50
6        2    80
7        2    90
8        3    20
9        3    50
10       3    65
11       3    45
12       4    46
13       4    48
14       4    75
15       4    58
16       5    65
17       5    80
18       5    89
19       5    78

### 변수 제거하기

In [25]:
exam.drop(columns='math') # math 제거

    id  nclass  english  science
0    1       1       98       50
1    2       1       97       60
2    3       1       86       78
3    4       1       98       58
4    5       2       80       65
5    6       2       89       98
6    7       2       90       45
7    8       2       78       25
8    9       3       98       15
9   10       3       98       45
10  11       3       65       65
11  12       3       85       32
12  13       4       98       65
13  14       4       87       12
14  15       4       56       78
15  16       4       98       65
16  17       5       68       98
17  18       5       78       90
18  19       5       68       87
19  20       5       83       58

In [26]:
exam.drop(columns=['math', 'english'])

    id  nclass  science
0    1       1       50
1    2       1       60
2    3       1       78
3    4       1       58
4    5       2       65
5    6       2       98
6    7       2       45
7    8       2       25
8    9       3       15
9   10       3       45
10  11       3       65
11  12       3       32
12  13       4       65
13  14       4       12
14  15       4       78
15  16       4       65
16  17       5       98
17  18       5       90
18  19       5       87
19  20       5       58

### pandas 함수 조합하기

In [27]:
# nclass가 1인  행만 추출한 다음 english추출
exam.query('nclass==1')['english']

0    98
1    97
2    86
3    98
Name: english, dtype: int64

In [28]:
# math가 50이상인 행만 추출한 다음 id, math 추출
exam.query('math>=50')[['id', 'math']]

    id  math
0    1    50
1    2    60
5    6    50
6    7    80
7    8    90
9   10    50
10  11    65
14  15    75
15  16    58
16  17    65
17  18    80
18  19    89
19  20    78

## 6-4 순서대로 정렬하기

### 오름차순 정렬하기

In [29]:
exam.sort_values('math')

    id  nclass  math  english  science
8    9       3    20       98       15
4    5       2    25       80       65
3    4       1    30       98       58
2    3       1    45       86       78
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
0    1       1    50       98       50
9   10       3    50       98       45
5    6       2    50       89       98
15  16       4    58       98       65
1    2       1    60       97       60
10  11       3    65       65       65
16  17       5    65       68       98
14  15       4    75       56       78
19  20       5    78       83       58
17  18       5    80       78       90
6    7       2    80       90       45
18  19       5    89       68       87
7    8       2    90       78       25

### 내림차순 정렬하기

In [30]:
exam.sort_values('math', ascending=False)

    id  nclass  math  english  science
7    8       2    90       78       25
18  19       5    89       68       87
6    7       2    80       90       45
17  18       5    80       78       90
19  20       5    78       83       58
14  15       4    75       56       78
10  11       3    65       65       65
16  17       5    65       68       98
1    2       1    60       97       60
15  16       4    58       98       65
0    1       1    50       98       50
5    6       2    50       89       98
9   10       3    50       98       45
13  14       4    48       87       12
12  13       4    46       98       65
2    3       1    45       86       78
11  12       3    45       85       32
3    4       1    30       98       58
4    5       2    25       80       65
8    9       3    20       98       15

### 여러 정렬 기준 적용하기

In [31]:
# nclass, math 오름차순 정렬
exam.sort_values(['nclass', 'math'])

    id  nclass  math  english  science
3    4       1    30       98       58
2    3       1    45       86       78
0    1       1    50       98       50
1    2       1    60       97       60
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
11  12       3    45       85       32
9   10       3    50       98       45
10  11       3    65       65       65
12  13       4    46       98       65
13  14       4    48       87       12
15  16       4    58       98       65
14  15       4    75       56       78
16  17       5    65       68       98
19  20       5    78       83       58
17  18       5    80       78       90
18  19       5    89       68       87

In [32]:
# nclass 오름차순, math 내림차순 정렬
exam.sort_values(['nclass', 'math'], ascending=[True, False])

    id  nclass  math  english  science
1    2       1    60       97       60
0    1       1    50       98       50
2    3       1    45       86       78
3    4       1    30       98       58
7    8       2    90       78       25
6    7       2    80       90       45
5    6       2    50       89       98
4    5       2    25       80       65
10  11       3    65       65       65
9   10       3    50       98       45
11  12       3    45       85       32
8    9       3    20       98       15
14  15       4    75       56       78
15  16       4    58       98       65
13  14       4    48       87       12
12  13       4    46       98       65
18  19       5    89       68       87
17  18       5    80       78       90
19  20       5    78       83       58
16  17       5    65       68       98

## 6-5 파생변수 추가하기

### 파생변수 추가하기

In [33]:
# total 변수 추가
exam.assign(total = exam['math']+exam['english']+exam['science'])

    id  nclass  math  english  science  total
0    1       1    50       98       50    198
1    2       1    60       97       60    217
2    3       1    45       86       78    209
3    4       1    30       98       58    186
4    5       2    25       80       65    170
5    6       2    50       89       98    237
6    7       2    80       90       45    215
7    8       2    90       78       25    193
8    9       3    20       98       15    133
9   10       3    50       98       45    193
10  11       3    65       65       65    195
11  12       3    45       85       32    162
12  13       4    46       98       65    209
13  14       4    48       87       12    147
14  15       4    75       56       78    209
15  16       4    58       98       65    221
16  17       5    65       68       98    231
17  18       5    80       78       90    248
18  19       5    89       68       87    244
19  20       5    78       83       58    219

In [34]:
# 한 번에 여러 파생변수 추가하기
exam.assign(
    total = exam['math'] + exam['english'] + exam['science'],
    mean = (exam['math'] + exam['english'] + exam['science']) / 3
)

    id  nclass  math  english  science  total       mean
0    1       1    50       98       50    198  66.000000
1    2       1    60       97       60    217  72.333333
2    3       1    45       86       78    209  69.666667
3    4       1    30       98       58    186  62.000000
4    5       2    25       80       65    170  56.666667
5    6       2    50       89       98    237  79.000000
6    7       2    80       90       45    215  71.666667
7    8       2    90       78       25    193  64.333333
8    9       3    20       98       15    133  44.333333
9   10       3    50       98       45    193  64.333333
10  11       3    65       65       65    195  65.000000
11  12       3    45       85       32    162  54.000000
12  13       4    46       98       65    209  69.666667
13  14       4    48       87       12    147  49.000000
14  15       4    75       56       78    209  69.666667
15  16       4    58       98       65    221  73.666667
16  17       5    65       68       98    231  77.000000
17  18       5    80       78       90    248  82.666667
18  19       5    89       68       87    244  81.333333
19  20       5    78       83       58    219  73.000000

### df.assign()에 np.where() 적용하기

In [35]:
exam.assign(test = np.where(exam['science'] >= 60, 'pass', 'fail'))

    id  nclass  math  english  science  test
0    1       1    50       98       50  fail
1    2       1    60       97       60  pass
2    3       1    45       86       78  pass
3    4       1    30       98       58  fail
4    5       2    25       80       65  pass
5    6       2    50       89       98  pass
6    7       2    80       90       45  fail
7    8       2    90       78       25  fail
8    9       3    20       98       15  fail
9   10       3    50       98       45  fail
10  11       3    65       65       65  pass
11  12       3    45       85       32  fail
12  13       4    46       98       65  pass
13  14       4    48       87       12  fail
14  15       4    75       56       78  pass
15  16       4    58       98       65  pass
16  17       5    65       68       98  pass
17  18       5    80       78       90  pass
18  19       5    89       68       87  pass
19  20       5    78       83       58  fail

### 추가한 변수를 pandas 함수에 바로 활용하기

In [36]:
exam.assign(total = exam['math'] + exam['english'] + exam['science']).sort_values('total')

    id  nclass  math  english  science  total
8    9       3    20       98       15    133
13  14       4    48       87       12    147
11  12       3    45       85       32    162
4    5       2    25       80       65    170
3    4       1    30       98       58    186
9   10       3    50       98       45    193
7    8       2    90       78       25    193
10  11       3    65       65       65    195
0    1       1    50       98       50    198
12  13       4    46       98       65    209
14  15       4    75       56       78    209
2    3       1    45       86       78    209
6    7       2    80       90       45    215
1    2       1    60       97       60    217
19  20       5    78       83       58    219
15  16       4    58       98       65    221
16  17       5    65       68       98    231
5    6       2    50       89       98    237
18  19       5    89       68       87    244
17  18       5    80       78       90    248

### lambda 이용해 데이터 프레임명 줄여 쓰기

In [37]:
long_name = pd.read_csv('data/exam.csv')

long_name.assign(new = long_name['math'] + long_name['english'] + long_name['science'])

    id  nclass  math  english  science  new
0    1       1    50       98       50  198
1    2       1    60       97       60  217
2    3       1    45       86       78  209
3    4       1    30       98       58  186
4    5       2    25       80       65  170
5    6       2    50       89       98  237
6    7       2    80       90       45  215
7    8       2    90       78       25  193
8    9       3    20       98       15  133
9   10       3    50       98       45  193
10  11       3    65       65       65  195
11  12       3    45       85       32  162
12  13       4    46       98       65  209
13  14       4    48       87       12  147
14  15       4    75       56       78  209
15  16       4    58       98       65  221
16  17       5    65       68       98  231
17  18       5    80       78       90  248
18  19       5    89       68       87  244
19  20       5    78       83       58  219

In [38]:
long_name.assign(new = lambda x: x['math'] + x['english'] + x['science']) # 위와 동일한 코드

    id  nclass  math  english  science  new
0    1       1    50       98       50  198
1    2       1    60       97       60  217
2    3       1    45       86       78  209
3    4       1    30       98       58  186
4    5       2    25       80       65  170
5    6       2    50       89       98  237
6    7       2    80       90       45  215
7    8       2    90       78       25  193
8    9       3    20       98       15  133
9   10       3    50       98       45  193
10  11       3    65       65       65  195
11  12       3    45       85       32  162
12  13       4    46       98       65  209
13  14       4    48       87       12  147
14  15       4    75       56       78  209
15  16       4    58       98       65  221
16  17       5    65       68       98  231
17  18       5    80       78       90  248
18  19       5    89       68       87  244
19  20       5    78       83       58  219

In [39]:
#  앞에서 만든 변수를 활용해 다시 변수만들기
# exam.assign(total = exam['math'] + exam['english'] + exam['science'], 
#             mean = exam['total']/ 3) # 키에러 발생 total이라는 키가 없음. 실행시 오류

In [40]:
# 변수를 다시 활용할 때는 람다를 사용해야 에러가 발생하지 않음
exam.assign(total = exam['math'] + exam['english'] + exam['science'], 
            mean = lambda x : x['total']/ 3)

    id  nclass  math  english  science  total       mean
0    1       1    50       98       50    198  66.000000
1    2       1    60       97       60    217  72.333333
2    3       1    45       86       78    209  69.666667
3    4       1    30       98       58    186  62.000000
4    5       2    25       80       65    170  56.666667
5    6       2    50       89       98    237  79.000000
6    7       2    80       90       45    215  71.666667
7    8       2    90       78       25    193  64.333333
8    9       3    20       98       15    133  44.333333
9   10       3    50       98       45    193  64.333333
10  11       3    65       65       65    195  65.000000
11  12       3    45       85       32    162  54.000000
12  13       4    46       98       65    209  69.666667
13  14       4    48       87       12    147  49.000000
14  15       4    75       56       78    209  69.666667
15  16       4    58       98       65    221  73.666667
16  17       5    65       68       98    231  77.000000
17  18       5    80       78       90    248  82.666667
18  19       5    89       68       87    244  81.333333
19  20       5    78       83       58    219  73.000000

In [41]:
exam.assign(total = lambda x : x['math'] + x['english'] + x['science'], 
            mean = lambda x : x['total']/ 3) # 가독성을 위해 모든 변수를 lambda를 사용하여 생성가능

    id  nclass  math  english  science  total       mean
0    1       1    50       98       50    198  66.000000
1    2       1    60       97       60    217  72.333333
2    3       1    45       86       78    209  69.666667
3    4       1    30       98       58    186  62.000000
4    5       2    25       80       65    170  56.666667
5    6       2    50       89       98    237  79.000000
6    7       2    80       90       45    215  71.666667
7    8       2    90       78       25    193  64.333333
8    9       3    20       98       15    133  44.333333
9   10       3    50       98       45    193  64.333333
10  11       3    65       65       65    195  65.000000
11  12       3    45       85       32    162  54.000000
12  13       4    46       98       65    209  69.666667
13  14       4    48       87       12    147  49.000000
14  15       4    75       56       78    209  69.666667
15  16       4    58       98       65    221  73.666667
16  17       5    65       68       98    231  77.000000
17  18       5    80       78       90    248  82.666667
18  19       5    89       68       87    244  81.333333
19  20       5    78       83       58    219  73.000000

## 6-6 집단별로 요약하기

### 집단별로 요약하기

In [42]:
# math 평균 구하기
exam.agg(mean_math = ('math', 'mean'))

            math
mean_math  57.45

In [43]:
# 집단별 요약 통계량 구하기
exam.groupby('nclass').agg(mean_math = ('math', 'mean'))

        mean_math
nclass
1           46.25
2           61.25
3           45.00
4           56.75
5           78.00

In [44]:
# 변수를 인덱스로 바꾸지 않기
exam.groupby('nclass', as_index=False).agg(mean_math = ('math', 'mean'))

   nclass  mean_math
0       1      46.25
1       2      61.25
2       3      45.00
3       4      56.75
4       5      78.00

In [45]:
# 여러 요약통계량 한 번에 구해가
exam.groupby('nclass', as_index=False)\
    .agg(mean_math = ('math', 'mean'),
         sum_math = ('math', 'sum'),
         median_math = ('math', 'median'),
         n = ('nclass' , 'count'))

   nclass  mean_math  sum_math  median_math  n
0       1      46.25       185         47.5  4
1       2      61.25       245         65.0  4
2       3      45.00       180         47.5  4
3       4      56.75       227         53.0  4
4       5      78.00       312         79.0  4

`agg()`에 자주 사용되는 요약 통계량
|함수|통계량|
|---|---|
|`mean()`|평균|
|`std()`|표준편차|
|`sum()`|합계|
|`median()`|중앙값|
|`min()`|최솟값|
|`max()`|최댓값|

### 집단별로 다시 집단 나누기

In [46]:
mpg = pd.read_csv('data/mpg.csv')

In [47]:
mpg.groupby(['manufacturer', 'drv']).agg(mean_cty = ('cty', 'mean'))

                   mean_cty
manufacturer drv
audi         4    16.818182
             f    18.857143
chevrolet    4    12.500000
             f    18.800000
             r    14.100000
dodge        4    12.000000
             f    15.818182
ford         4    13.307692
             r    14.750000
honda        f    24.444444
hyundai      f    18.642857
jeep         4    13.500000
land rover   4    11.500000
lincoln      r    11.333333
mercury      4    13.250000
nissan       4    13.750000
             f    20.000000
pontiac      f    17.000000
subaru       4    19.285714
toyota       4    14.933333
             f    21.368421
volkswagen   f    20.925926

### pandas 함수 조합하기

In [48]:
# Q. 제조회사 별로 'suv' 자동차의 도시 및 고속도로 합산 연비 평균을 구해 내림차순으로 정렬하고, 1~5위까지 출력하기
mpg.query('category == "suv"').assign(total = (mpg['cty'] + mpg['hwy'])/2).groupby('manufacturer').agg(total_mean = ('total', 'mean')).sort_values('total_mean', ascending=False).head(5)

              total_mean
manufacturer
subaru         21.916667
toyota         16.312500
nissan         15.875000
mercury        15.625000
jeep           15.562500

## 6-7 데이터 합치기

### 가로로 합치기

In [49]:
test1 = pd.DataFrame({'id': [1, 2, 3, 4, 5],
                      'midterm': [60, 80, 70, 90, 85]})

test2 = pd.DataFrame({'id': [1, 2, 3, 4, 5],
                      'fianl': [70, 83, 65, 95, 80]})

In [50]:
test1

   id  midterm
0   1       60
1   2       80
2   3       70
3   4       90
4   5       85

In [51]:
test2

   id  fianl
0   1     70
1   2     83
2   3     65
3   4     95
4   5     80

In [52]:
total = pd.merge(test1, test2, how='left', on='id')
total

   id  midterm  fianl
0   1       60     70
1   2       80     83
2   3       70     65
3   4       90     95
4   5       85     80

In [53]:
# 다른 데이터를 활용해 변수 추가하기
name = pd.DataFrame({'nclass': [1, 2, 3, 4, 5],
                     'teacher': ['kim', 'lee', 'park', 'choi', 'jung']})

name

   nclass teacher
0       1     kim
1       2     lee
2       3    park
3       4    choi
4       5    jung

In [54]:
exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [55]:
exam_new = pd.merge(exam, name, how='left', on='nclass')
exam_new

    id  nclass  math  english  science teacher
0    1       1    50       98       50     kim
1    2       1    60       97       60     kim
2    3       1    45       86       78     kim
3    4       1    30       98       58     kim
4    5       2    25       80       65     lee
5    6       2    50       89       98     lee
6    7       2    80       90       45     lee
7    8       2    90       78       25     lee
8    9       3    20       98       15    park
9   10       3    50       98       45    park
10  11       3    65       65       65    park
11  12       3    45       85       32    park
12  13       4    46       98       65    choi
13  14       4    48       87       12    choi
14  15       4    75       56       78    choi
15  16       4    58       98       65    choi
16  17       5    65       68       98    jung
17  18       5    80       78       90    jung
18  19       5    89       68       87    jung
19  20       5    78       83       58    jung

### 세로로 합치기

In [56]:
group1 = pd.DataFrame({'id': [1, 2, 3, 4, 5],
                       'test': [60, 80, 70, 90, 85]})

group2 = pd.DataFrame({'id': [6, 7, 8, 9, 10],
                       'test': [70, 83, 65, 95, 80]})

group1

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85

In [57]:
group2

   id  test
0   6    70
1   7    83
2   8    65
3   9    95
4  10    80

In [58]:
group_all = pd.concat([group1, group2])
group_all

   id  test
0   1    60
1   2    80
2   3    70
3   4    90
4   5    85
0   6    70
1   7    83
2   8    65
3   9    95
4  10    80

## 과제

미국 동북중부 437지역의 인구 통계 정보를 담고 있는 `midwest.csv`를 사용해 데이터 분석 문제를 해결해 보세요.

In [78]:
midwest = pd.read_csv('data/midwest.csv')
midwest.head()

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,...,percollege,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,19.631392,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,11.243308,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,17.033819,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,17.278954,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,14.475999,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR

### 문제 1. `popadults`는 해당 지역의 성인 인구, `poptotal`은 전체 인구를 나타냅니다. `midwest`데이터에 '전체 인구 대비 미성년 인구 백분율' 변수를 추가하세요.

In [81]:
midwest = midwest.assign(minor_pop_ratio = lambda x: (x['poptotal'] - x['popadults'])/x['poptotal'] * 100)
midwest.head()

,PID,county,state,area,poptotal,popdensity,popwhite,popblack,popamerindian,popasian,...,percprof,poppovertyknown,percpovertyknown,percbelowpoverty,percchildbelowpovert,percadultpoverty,percelderlypoverty,inmetro,category,minor_pop_ratio
0,561,ADAMS,IL,0.052,66090,1270.961540,63917,1702,98,249,...,4.355859,63628,96.274777,13.151443,18.011717,11.009776,12.443812,0,AAR,34.486307
1,562,ALEXANDER,IL,0.014,10626,759.000000,7054,3496,19,48,...,2.870315,10529,99.087145,32.244278,45.826514,27.385647,25.228976,0,LHR,36.721250
2,563,BOND,IL,0.022,14991,681.409091,14477,429,35,16,...,4.488572,14235,94.956974,12.068844,14.036061,10.852090,12.697410,0,AAR,35.501301
3,564,BOONE,IL,0.017,30806,1812.117650,29344,127,46,150,...,4.197800,30337,98.477569,7.209019,11.179536,5.536013,6.217047,1,ALU,37.440758
4,565,BROWN,IL,0.018,5836,324.222222,5264,547,14,5,...,3.367680,4815,82.505140,13.520249,13.022889,11.143211,19.200000,0,AAR,31.819740

### 문제 2. 미성년 인구 백분율이 가장 높은 상위 5개 `county`(지역)의 미성년 인구 백분율을 출력하세요.

In [82]:
midwest.sort_values('minor_pop_ratio', ascending=False)[['county', 'minor_pop_ratio']].head(5)

        county  minor_pop_ratio
230   ISABELLA        51.501172
404  MENOMINEE        50.591260
281     ATHENS        49.320727
247    MECOSTA        49.059183
154     MONROE        47.358182

### 문제 3. 분류표의 기준에 따라 미성년 비율 등급 변수를 추가하고, 각 등급에 몇 개의 지역이 있는지 알아보세요.
|분류|기준|
|---|---|
|large|40% 이상|
|middle|30~40% 이상|
|small|30% 미만|

In [83]:
midwest = midwest.assign(minor_grade = lambda x: np.where(x['minor_pop_ratio'] >=  40, 'large', 
                                                np.where(x['minor_pop_ratio'] >= 30, 'middle', 'small')), inplace =True)

midwest['minor_grade'].value_counts()

minor_grade
middle    396
large      32
small       9
Name: count, dtype: int64

### 문제 4. `popasian`은 해당 지역의 아시아인 인구를 나타냅니다. '전체 인구 대비 아시아인 인구 백분률' 변수를 추가하고 하위 10개 지역의 `state`(주), `county`(지역), 아시아인 인구 백분율을 출력하세요.

In [86]:
midwest = midwest.assign(asian_ratio = lambda x: x['popasian']/x['poptotal']*100).sort_values('asian_ratio', ascending=True).reset_index()
midwest[['state', 'county', 'asian_ratio']].head(10)

  state     county  asian_ratio
0    WI  MENOMINEE     0.000000
1    IN     BENTON     0.010592
2    IN    CARROLL     0.015950
3    OH     VINTON     0.027032
4    WI       IRON     0.032504
5    IL      SCOTT     0.053154
6    IN       CLAY     0.060716
7    MI     OSCODA     0.063759
8    OH      PERRY     0.066546
9    IL      PIATT     0.070749