# CH 7. 데이터 정제 - 빠진 데이터, 이상한 데이터 제거하기

In [2]:
import pandas as pd
import numpy as np

## 7-1 이상치 제거하기

### 결측치 찾기

In [4]:
# 결측치를 포함하는 데이터 생성
df = pd.DataFrame({'sex': ['M', 'F', np.nan, 'M', 'F'],
                   'score': [5, 4, 3, 4, np.nan]})
df

   sex  score
0    M    5.0
1    F    4.0
2  NaN    3.0
3    M    4.0
4    F    NaN

In [6]:
# 결측치 확인하기
pd.isna(df)

     sex  score
0  False  False
1  False  False
2   True  False
3  False  False
4  False   True

In [9]:
pd.isna(df).sum()

sex      1
score    1
dtype: int64

### 결측치 제거하기

In [ ]:
df.dropna(subset='score') # 하나의 속성에 대한 결측치 제거

   sex  score
0    M    5.0
1    F    4.0
2  NaN    3.0
3    M    4.0

In [13]:
df.dropna(subset=['sex', 'score']) # 여러 개의 속성에 대한 결측치 제거

  sex  score
0   M    5.0
1   F    4.0
3   M    4.0

In [14]:
df.dropna() # 모든 결측치가 있는 행 제거

  sex  score
0   M    5.0
1   F    4.0
3   M    4.0

### 결측치 대체하기

In [18]:
exam = pd.read_csv('data/exam.csv')
exam.loc[[2, 7, 14], ['math']] = np.nan
exam

    id  nclass  math  english  science
0    1       1  50.0       98       50
1    2       1  60.0       97       60
2    3       1   NaN       86       78
3    4       1  30.0       98       58
4    5       2  25.0       80       65
5    6       2  50.0       89       98
6    7       2  80.0       90       45
7    8       2   NaN       78       25
8    9       3  20.0       98       15
9   10       3  50.0       98       45
10  11       3  65.0       65       65
11  12       3  45.0       85       32
12  13       4  46.0       98       65
13  14       4  48.0       87       12
14  15       4   NaN       56       78
15  16       4  58.0       98       65
16  17       5  65.0       68       98
17  18       5  80.0       78       90
18  19       5  89.0       68       87
19  20       5  78.0       83       58

In [21]:
mean_math = exam['math'].mean() # mean 매서드는 결측치가 있어도 작동
mean_math

np.float64(55.23529411764706)

In [23]:
exam['math'] = exam['math'].fillna(mean_math) # 평균으로 결측치 대체하기
exam

    id  nclass       math  english  science
0    1       1  50.000000       98       50
1    2       1  60.000000       97       60
2    3       1  55.235294       86       78
3    4       1  30.000000       98       58
4    5       2  25.000000       80       65
5    6       2  50.000000       89       98
6    7       2  80.000000       90       45
7    8       2  55.235294       78       25
8    9       3  20.000000       98       15
9   10       3  50.000000       98       45
10  11       3  65.000000       65       65
11  12       3  45.000000       85       32
12  13       4  46.000000       98       65
13  14       4  48.000000       87       12
14  15       4  55.235294       56       78
15  16       4  58.000000       98       65
16  17       5  65.000000       68       98
17  18       5  80.000000       78       90
18  19       5  89.000000       68       87
19  20       5  78.000000       83       58

In [25]:
exam['math'].isna().sum()

np.int64(0)

## 7-2 이상치 정제하기

### 이상치 제거하기 - 존재할 수 없는 값

In [27]:
df = pd.DataFrame({'sex': [1, 2, 1, 3, 2, 1], # 성별은 1과 2로 구분 3은 이상치
                   'score': [5, 4, 3, 4, 2, 6]}) # score는 1~5점을 가짐, 6은 이상치
df

   sex  score
0    1      5
1    2      4
2    1      3
3    3      4
4    2      2
5    1      6

In [28]:
# 이상치 확인하기
df['sex'].value_counts()

sex
1    3
2    2
3    1
Name: count, dtype: int64

In [29]:
df['score'].value_counts()

score
4    2
5    1
3    1
2    1
6    1
Name: count, dtype: int64

In [30]:
# 결측치로 변환하기
df['sex'] = np.where(df['sex']==3, np.nan, df['sex'])
df['score'] = np.where(df['score']>=5, np.nan, df['score'])
df

   sex  score
0  1.0    NaN
1  2.0    4.0
2  1.0    3.0
3  NaN    4.0
4  2.0    2.0
5  1.0    NaN

### 이상치 제거하기 - 극단적인 값